apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mycluster
spec:
  version: 8.9.2
  nodeSets:
  - name: master-nodes
    count: 2
    config:
      node.roles: ["master"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 2Gi
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: do-block-storage-retain
  - name: data-nodes
    count: 6
    config:
      node.roles: ["data"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
            limits:
              memory: 4Gi
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: do-block-storage-retain
  # - name: ingest-nodes
  #   count: 1
  #   config:
  #     node.roles: ["ingest", "transform"]
  #   podTemplate:
  #     spec:
  #       containers:
  #       - name: elasticsearch
  #         resources:
  #           requests:
  #             memory: 2Gi
  #           limits:
  #             memory: 2Gi
  #       initContainers:
  #       - name: sysctl
  #         securityContext:
  #           privileged: true
  #           runAsUser: 0
  #         command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  #   volumeClaimTemplates:
  #   - metadata:
  #       name: elasticsearch-data
  #     spec:
  #       accessModes:
  #       - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 3Gi
  #       storageClassName: standard
