apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: mycluster
spec:
  version: 8.9.2
  nodeSets:
  - name: master-nodes
    count: 2
    config:
      node.roles: ["master"]
  - name: data-nodes
    count: 3
    config:
      node.roles: ["data"]
