apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eck-ingress
  namespace: eck
  # annotations:
  #   cert-manager.io/issuer: eck-issuer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  # tls:
  #   - hosts:
  #       - mycluster.com
  #     secretName: eck-issuer-secret
  rules:
  - host: mycluster.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mycluster-es-http
            port:
              number: 8080
  # ingressClassName: nginxkubectl get ingress
