spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/sspfinc/eck
    targetRevision: main

applications:
- name: elasticsearch
  enabled: true
  syncWave: "3"

- name: kibana
  enabled: true
  syncWave: "4"

- name: argocd
  enabled: true
  syncWave: "-5"

- name: monitoring
  enabled: true
  syncWave: "-5"


- name: cert-manager
  enabled: true
  syncWave: "0"
  createNamespace: true
  helm:
    parameters:
    - name: installCRDs
      value: 'true'
    - name: prometheus.servicemonitor.enabled
      value: 'false'
    - name: prometheus.servicemonitor.honorLabels
      value: 'false'
  repoURL: https://charts.jetstack.io
  targetRevision: v1.9.2

- name: traefik
  enabled: true
  syncWave: "-2"
  createNamespace: true
  repoURL: https://traefik.github.io/charts
  targetRevision: v24.0.0

- name: trivy-operator
  enabled: false
  syncWave: "2"
  namespace: trivy-system
  createNamespace: true
  repoURL: https://aquasecurity.github.io/helm-charts/
  targetRevision: v0.10.1
  helm:
    values: |
      serviceMonitor:
        enabled: false # has to be false if you do not have Prometheus already installed
      trivy:
        ignoreUnfixed: true

- name: kube-prometheus-stack
  enabled: true
  syncWave: "2"
  namespace: monitoring
  createNamespace: true
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: v51.0.3
  helm:
    values: |
      prometheus.prometheusSpec.externalUrl: https://prometheus.petersfarber.com/prometheus
      prometheusOperator.admissionWebhooks.enabled: false
      prometheusOperator.admissionWebhooks.patch.enabled: false
      prometheusOperator.tlsProxy.enabled: false


