spec:
  destination:
    # HIGHLIGHT
    server: https://kubernetes.default.svc
  source:
    # HIGHLIGHT
    repoURL: https://github.com/sspfinc/eck
    # HIGHLIGHT
    targetRevision: main

# HIGHLIGHT
applications:
- name: elasticsearch
  enabled: true
  syncWave: "1"
- name: kibana
  enabled: true
  syncWave: "2"

traefik:
  enable: true
