apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: cert-manager
    repoURL: {? {.Values.default.repoURL: ''} : ''}
    targetRevision: HEAD
  destination:
    server: {? {.Values.default.server: ''} : ''}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
