apiVersion: apps/v1
kind: Deployment
metadata:
  name: eck-search-api
  namespace: eck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eck-search-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eck-search-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: eck-search-api
        image: sspf/eck-search-api
        env:
        - name: ELASTIC_NODE
          valueFrom:
            secretKeyRef:
              name: eck-search-api-secret
              key: ELASTIC_NODE
        - name: ELASTIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: eck-search-api-secret
              key: ELASTIC_API_KEY
        - name: ELASTIC_CA
          valueFrom:
            configMapKeyRef:
              name: eck-search-api-config-map
              key: ELASTIC_CA
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: eck-search-api-config-map
              key: NODE_ENV
        - name: ROLE
          valueFrom:
            configMapKeyRef:
              name: eck-search-api-config-map
              key: ROLE
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: eck-search-api-secret
          mountPath: /secrets
          readOnly: true
        - name: eck-search-api-config-map
          mountPath: /config
          readOnly: true
      volumes:
      - name: eck-search-api-config-map
        configMap:
          name: eck-search-api-config-map
      - name: eck-search-api-secret
        secret:
          secretName: eck-search-api-secret
