apiVersion: apps/v1
kind: Deployment
metadata:
  name: eck-search-ui
  namespace: eck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eck-search-ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eck-search-ui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: eck-search-ui
        image: sspf/eck-search-ui
        ports:
        - name: http
          containerPort: 3000

