apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-eck-search-ui
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: traefik
  rules:
  - host: eck-search-ui.sspf.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eck-search-ui
            port:
              number: 80
  tls:
  - secretName: eck-search-ui-secret-tls
    hosts:
    - eck-search-ui.sspf.app
