apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kibana
    repoURL: {{.Values.default.repoURL}}
    targetRevision: HEAD
  destination:
    server: {{.Values.default.server}}
    namespace: eck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
