apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-nyc1
spec:
  version: 8.9.2
  count: 1
  elasticsearchRef:
    name: cluster-nyc1
  config:
    server.publicBaseUrl: https://kibana.petersfarber.com
  http:
    tls:
      selfSignedCertificate:
        disabled: true
