apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-argocd-issuer
  namespace: argocd
spec:
  acme:
    email: peter@capsl8.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-argocd-key
    solvers:
    - selector: {}
      dns01:
        digitalocean:
          tokenSecretRef:
            name: lets-encrypt-do-dns
            key: access-token
